const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || '/opt/node22/lib/node_modules/playwright/index.mjs');
const base = process.argv[2];
const b = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true, reducedMotion: 'reduce' });
const p = await ctx.newPage(); p.setDefaultTimeout(8000);
const errors = []; p.on('pageerror', e => errors.push(e.message));
let rsc = 0, docs = 0;
p.on('request', r => { if (r.url().includes('.rsc') || r.headers()['rsc'] || r.headers()['accept']?.includes('text/x-component')) rsc++; if (r.resourceType() === 'document') docs++; });
await p.goto('about:blank'); await p.goto(base, { waitUntil: 'networkidle' }); await p.waitForSelector('.today-view');
await p.evaluate(() => { window.__marker = 1; });
const results = [];
const check = async (name, fn, expect) => { await fn(); await p.waitForTimeout(500); const ok = await expect(); results.push(`${ok ? 'PASS' : 'FAIL'} ${name}`); };
const rscBefore = () => rsc;
await check('lexicon -> back -> today', async () => { await p.locator('.mobile-nav button:has-text("词库")').click(); await p.waitForSelector('.word-row'); await p.goBack(); }, () => p.locator('.today-view').isVisible());
await check('word detail -> back closes dialog, stays in lexicon', async () => { await p.locator('.mobile-nav button:has-text("词库")').click(); await p.locator('.word-open').first().click(); await p.waitForSelector('dialog[open]'); await p.goBack(); }, async () => !(await p.locator('dialog[open]').count()) && await p.locator('.word-row').first().isVisible());
await check('lexicon -> back -> today (after dialog)', async () => { await p.goBack(); }, () => p.locator('.today-view').isVisible());
await check('flashcards -> back -> today', async () => { await p.locator('.practice-option:has-text("词卡速记")').click(); await p.waitForTimeout(500); await p.goBack(); }, () => p.locator('.today-view').isVisible());
await check('practice -> back -> today with resume', async () => { await p.locator('.daily-feature button.primary').click(); await p.waitForSelector('.study-screen'); await p.keyboard.press('Space'); await p.waitForTimeout(300); await p.keyboard.press('3'); await p.waitForTimeout(400); await p.goBack(); }, async () => (await p.locator('.today-view').isVisible()) && (await p.locator('text=继续学习').count()) > 0);
await check('UI close then back leaves nothing stale (lexicon via tab, today via tab)', async () => { await p.locator('.mobile-nav button:has-text("词库")').click(); await p.waitForTimeout(300); await p.locator('.mobile-nav button:has-text("今日")').click(); await p.waitForTimeout(500); }, async () => !(await p.evaluate(() => history.state?.__vocabBackGuard)));
await check('no reload happened', async () => {}, () => p.evaluate(() => window.__marker === 1));
await check('back at today leaves the app', async () => { await p.goBack(); }, async () => p.url() === 'about:blank');
console.log(results.join('\n')); console.log({ rscRequests: rsc, documentRequests: docs, errors });
await b.close();
if (results.some(r => r.startsWith('FAIL')) || errors.length) process.exitCode = 1;
