"use client";
import { Check, Keyboard, MoveHorizontal, RotateCcw, Undo2, Volume2, X, Zap } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import type { SessionState } from "@/components/vocab-app";
import type { LexiconDetail, LexiconIndexEntry } from "@/lib/lexicon";
import { localSentenceCheck, QUESTION_CATALOG, type Question, type QuestionType } from "@/lib/questions";
import { previewReviewIntervals } from "@/lib/scheduler";
import type { ReviewEvent, SkillName, StoredCard } from "@/lib/storage";
const labels:Record<SkillName,string>={meaning:"识义",listening:"听辨",spelling:"拼写",context:"语境",collocation:"搭配",output:"输出"};
const rating=["","忘记","困难","记得","轻松"];
function sourceLine(e:LexiconIndexEntry){const s=e.sources[0];return s?`${s.volume} · ${s.unit}${s.printedPage?` · p.${s.printedPage}`:""}`:"来源待核"}
function clock(ms:number){const s=Math.max(0,Math.floor(ms/1000));return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}
function Metric({label,value,note}:{label:string;value:string|number;note?:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
export type ConsoleStudyProps={saving:boolean;session:SessionState;complete:boolean;entry:LexiconIndexEntry|null;detail?:LexiconDetail;card?:StoredCard;events:ReviewEvent[];index:LexiconIndexEntry[];desiredRetention:number;dailyMinutes:number;question:Question|null;answer:string;setAnswer:(v:string)=>void;revealed:boolean;objectiveResult:boolean|null;hints:number;setHints:(v:number)=>void;onCheck:()=>void;onRate:(r:1|2|3|4)=>void;onExit:()=>void;onRestart:()=>void;onSpeak:()=>void;onUndo:()=>void;canUndo:boolean;forcedType:QuestionType|null;setForcedType:(t:QuestionType|null)=>void};
export default function ConsoleStudySession(p:ConsoleStudyProps){
 const{saving,session,complete,entry,detail,card,events,index,desiredRetention,dailyMinutes,question,answer,setAnswer,revealed,objectiveResult,hints,setHints,onCheck,onRate,onExit,onRestart,onSpeak,onUndo,canUndo,forcedType,setForcedType}=p;
 const[now,setNow]=useState(session.startedAt),touch=useRef<{x:number;y:number}|null>(null);
 useEffect(()=>{const t=window.setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);
 const intervals=useMemo(()=>previewReviewIntervals(card,desiredRetention),[card,desiredRetention]);
 const byId=useMemo(()=>new Map(index.map(e=>[e.id,e])),[index]);
 const rel=(ids?:string[])=>(ids||[]).map(id=>byId.get(id)).filter(Boolean) as LexiconIndexEntry[];
 const family=rel(detail?.relations.family),phrases=rel(detail?.relations.phrases),confusables=rel(detail?.relations.confusables);
 const entryEvents=entry?[...events].filter(e=>e.cardId===entry.id).sort((a,b)=>b.timestampUtc.localeCompare(a.timestampUtc)):[];
 const mistakes=entryEvents.filter(e=>!e.correct).slice(0,3),source=entry?.sources[0];
 const neighbors=entry?index.filter(e=>e.id!==entry.id&&e.sources.some(s=>source&&s.bookId===source.bookId&&s.unit===source.unit)).slice(0,4):[];
 const miss=[...events].sort((a,b)=>b.timestampUtc.localeCompare(a.timestampUtc)).findIndex(e=>!e.correct),streak=miss===-1?events.length:miss;
 if(complete){const elapsed=((session.endedAt||session.startedAt)-session.startedAt)/60000;return <main className="console-session complete-shell"><div className="session-complete"><span className="completion-mark"><Check size={30}/></span><p className="console-kicker">SESSION COMPLETE</p><h1>{session.kind==="diagnostic"?"诊断样本已写入计划。":"本轮学习完成。"}</h1><p>下一次仍会从到期词和薄弱能力开始。</p><div className="completion-metrics"><Metric label="完成" value={session.reviewed} note="主学习状态更新"/><Metric label="正确" value={`${Math.round(session.correct/Math.max(1,session.reviewed)*100)}%`} note="客观题 + 翻卡"/><Metric label="用时" value={`${Math.round(elapsed)} 分钟`} note="含思考与反馈"/></div><div className="button-row center">{canUndo&&<button className="console-secondary" disabled={saving} onClick={onUndo}><Undo2 size={17}/>撤销最后评分</button>}<button className="console-secondary" disabled={saving} onClick={onRestart}><RotateCcw size={17}/>再练一轮</button><button className="console-primary" disabled={saving} onClick={onExit}>返回今日</button></div></div></main>}
 if(!entry||!question)return null;
 const sentence=question.type==="sentence-output"&&answer?localSentenceCheck(answer,entry.headword):null,progress=(session.position+(revealed?.5:0))/session.queue.length,promptWord=question.type==="meaning-recall"||question.type==="textbook-context";
 const start=(e:React.TouchEvent)=>{const t=e.target as HTMLElement;if(!["INPUT","TEXTAREA","SELECT","BUTTON"].includes(t.tagName))touch.current={x:e.touches[0].clientX,y:e.touches[0].clientY}};
 const end=(e:React.TouchEvent)=>{if(!revealed||saving||!touch.current){touch.current=null;return;}const dx=e.changedTouches[0].clientX-touch.current.x,dy=e.changedTouches[0].clientY-touch.current.y;touch.current=null;if(Math.abs(dx)<72&&Math.abs(dy)<72)return;if(Math.abs(dx)>Math.abs(dy))onRate(dx>0?3:1);else if(dy<0)onRate(4)};
 return <main className="console-session" onTouchStart={start} onTouchEnd={end}>
  <header className="console-session-top"><button disabled={saving} onClick={onExit} aria-label="退出并保存"><X size={18}/></button><span>{session.kind==="diagnostic"?"分层诊断":session.kind==="free"?"自由练习":"今日学习 · 普通"}</span><div className="session-track"><i><b style={{width:`${progress*100}%`}}/></i><strong>{session.position+1}<em>/ {session.queue.length}</em></strong></div><time>{clock(now-session.startedAt)}</time><small>/ {dailyMinutes} 分钟</small><div className="correct-streak"><Zap size={14}/><span>连对 {Math.max(0,streak)}</span></div></header>
  <div className="console-session-body"><section className="console-study-main">
   <div className="console-question-meta"><label><span>{question.label}</span><select disabled={saving} value={forcedType||"adaptive"} onChange={e=>setForcedType(e.target.value==="adaptive"?null:e.target.value as QuestionType)} aria-label="选择题型"><option value="adaptive">自适应题型</option>{QUESTION_CATALOG.map(i=><option key={i.id} value={i.id}>{i.label}</option>)}</select></label><span>{sourceLine(entry)} · {detail?.fieldStatus.sources||"verified-primary"}</span></div>
   <article className="console-study-card"><div className="study-card-label">第 {session.position+1} 题 · {card?.lastReviewed?"到期复习":"新词"}</div>{question.audio&&<button className="console-audio" onClick={onSpeak}><Volume2 size={22}/><span>播放系统语音</span><kbd>R</kbd></button>}<p className={question.prompt.length>90?"console-study-prompt long":"console-study-prompt"}>{question.prompt}</p>{promptWord&&entry.britishIpa&&<div className="prompt-ipa"><span>BrE /{entry.britishIpa}/</span><button onClick={onSpeak}><Volume2 size={14}/>系统语音</button><small>{entry.partsOfSpeech.join(" · ")||detail?.kind||"词条"} · 出现于 {entry.sources.length} 处</small></div>}{question.support&&!promptWord&&<p className="console-study-support">{question.support}</p>}
    {!revealed&&question.inputMode==="text"&&<div className="console-answer-area"><input autoFocus value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>e.key==="Enter"&&onCheck()} placeholder="输入答案" spellCheck={false} autoComplete="off"/></div>}{!revealed&&question.inputMode==="textarea"&&<div className="console-answer-area"><textarea autoFocus value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="先独立作答；核心功能不依赖 AI"/>{sentence&&<p className={sentence.hasTarget&&sentence.completeEnough?"local-check pass":"local-check"}>{sentence.message}</p>}</div>}{!revealed&&question.inputMode==="choice"&&<div className="console-choice-grid">{question.choices.map(c=><button key={c} className={answer===c?"selected":""} onClick={()=>setAnswer(c)}><span/>{c}</button>)}</div>}
    {revealed&&<div className="console-answer-reveal">{objectiveResult!==null&&<div className={objectiveResult?"console-result correct":"console-result incorrect"}>{objectiveResult?<Check size={17}/>:<X size={17}/>}<strong>{objectiveResult?"客观判定正确":"客观判定未命中"}</strong>{answer&&<span>你的答案：{answer}</span>}</div>}<span className="answer-label">已翻卡 · 答案</span><h2>{question.answer}</h2>{question.type!=="meaning-recall"&&<p className="answer-meaning">{entry.chineseCore}</p>}{detail?.englishCore&&<p className="console-definition">{detail.englishCore}<small>{detail.license.englishDefinition||"开放词典许可见字段记录"}</small></p>}{detail?.openExample&&<div className="console-example"><span>开放语料例句</span><p>{detail.openExample}</p><small>未复制教材整段；例句来源与许可见词条记录</small></div>}{sentence&&<p className="local-check-note">本地用法检查：{sentence.message}</p>}</div>}
   </article>
   {!revealed?<div className="console-study-actions"><button className="console-hint" onClick={()=>setHints(hints+1)} disabled={hints>=2}>提示 {hints}/2</button><button className="console-primary" onClick={onCheck}>{question.inputMode==="reveal"?"显示答案":"核对答案"}<kbd>Space</kbd></button></div>:<div className="console-rating"><div><span>这次回忆有多费力？</span><small>键帽下方是评分后的真实下一次间隔</small></div><section>{intervals.map(i=><button key={i.rating} className={i.rating===3?"recommended":""} disabled={saving} onClick={()=>onRate(i.rating)}><strong>{rating[i.rating]}</strong><kbd>{i.rating}</kbd><span>{i.label}{i.rating===3?" · 推荐":""}</span></button>)}</section></div>}
   <footer className="console-session-help"><span><Keyboard size={14}/>Space 翻卡 / 下一题</span><span>R 发音</span><span>Z 撤销</span><span>1–4 评分</span><span className="mobile-gesture-hint"><MoveHorizontal size={14}/>左滑忘记 · 右滑记得 · 上滑轻松</span></footer>
  </section><aside className="console-context"><h2>上下文 · 常驻</h2>{family.length>0&&<section><h3>词族</h3><div className="context-chips">{family.map(e=><span key={e.id}>{e.headword}<em>{e.partsOfSpeech[0]||""}</em></span>)}</div></section>}{phrases.length>0&&<section><h3>已审核短语</h3>{phrases.slice(0,5).map(e=><div className="context-row" key={e.id}><strong>{e.headword}</strong><small>{e.chineseCore} · {sourceLine(e)}</small></div>)}</section>}{confusables.length>0&&<section><h3>易混</h3><div className="context-chips">{confusables.map(e=><span key={e.id}>{e.headword}</span>)}</div></section>}<section><h3>你此前错在哪</h3>{mistakes.length?mistakes.map(e=><div className="mistake-row" key={e.eventId}><strong>{labels[e.skill]} · {e.errorType||"回忆"}</strong><p>{e.answerGiven?<>写成 <b>{e.answerGiven}</b></>:"主观评分为忘记"}{e.expectedAnswer&&e.answerGiven?<>；答案 <b>{e.expectedAnswer}</b></>:null}</p><small>{new Date(e.timestampUtc).toLocaleDateString("zh-CN")}</small></div>):<p className="context-empty">本词还没有未命中记录。</p>}</section>{neighbors.length>0&&<section><h3>同单元邻词</h3>{neighbors.map(e=><div className="neighbor-row" key={e.id}><span><strong>{e.headword}</strong><small>{e.chineseCore}</small></span><em>查看</em></div>)}</section>}<section className="context-fsrs"><h3>FSRS 主状态</h3><div><span>复习次数<strong>{entryEvents.length}</strong></span><span>稳定度<strong>{Number(card?.fsrs.stability||0).toFixed(1)}</strong></span><span>难度<strong>{Number(card?.fsrs.difficulty||0).toFixed(1)}</strong></span></div><p>评分只更新此词唯一的主状态。</p></section></aside></div>
 </main>
}
